// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	chat "github.com/acger/chat-api/internal/handler/chat"
	"github.com/acger/chat-api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/chat/message",
				Handler: chat.ChatMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/chat/message/save",
				Handler: chat.ChatMessageSaveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/chat/history",
				Handler: chat.ChatHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/chat/history/save",
				Handler: chat.ChatHistorySaveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/chat/history/number",
				Handler: chat.ChatHistoryNumberHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
